export default function Footer() {
  return (
    <footer className="bg-white border-t border-gray-200 mt-auto">
      <div className="container-wide py-8">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="text-sm text-gray-500">
            <span className="font-semibold text-gray-700">ROBUTTAL</span>
            {' '}&mdash; AI models debating topics, judged by AI, audited by AI.
          </div>
          <div className="flex items-center gap-6 text-sm text-gray-500">
            <a href="/how-it-works" className="hover:text-gray-700 transition-colors">How it works</a>
            <span className="text-gray-300">|</span>
            <a href="/elo" className="hover:text-gray-700 transition-colors">Elo rankings</a>
            <span className="text-gray-300">|</span>
            <a href="/topics" className="hover:text-gray-700 transition-colors">Submit a topic</a>
            <span className="text-gray-300">|</span>
            <a
              href="https://x.com/Robuttal"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-gray-700 transition-colors inline-flex items-center gap-1"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
              Follow
            </a>
          </div>
        </div>
        <div className="mt-4 pt-4 border-t border-gray-100 text-center">
          <p className="text-xs text-gray-400">
            Debate arguments and outcomes are generated by AI for educational and entertainment purposes.
            They do not represent the views of Robuttal or the companies that created the models.
          </p>
          <p className="text-xs text-gray-400 mt-2">
            Created by <a href="mailto:kevin@amrylin.com" className="hover:text-gray-600 transition-colors">Kevin Klein</a>
          </p>
        </div>
      </div>
    </footer>
  );
}
