"""add_analytics_columns_scores_and_tokens

Revision ID: 08253d9fce42
Revises: 98c35fbf9f7d
Create Date: 2025-11-28 22:02:26.645493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08253d9fce42'
down_revision: Union[str, None] = '98c35fbf9f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('pro_logical_consistency', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('pro_evidence', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('pro_persuasiveness', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('pro_engagement', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_logical_consistency', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_evidence', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_persuasiveness', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_engagement', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('audit_accuracy', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('audit_fairness', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('audit_thoroughness', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('audit_reasoning_quality', sa.Integer(), nullable=True))
    op.add_column('transcript_entries', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('transcript_entries', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('transcript_entries', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('transcript_entries', sa.Column('cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_entries', 'cost_usd')
    op.drop_column('transcript_entries', 'latency_ms')
    op.drop_column('transcript_entries', 'output_tokens')
    op.drop_column('transcript_entries', 'input_tokens')
    op.drop_column('debates', 'audit_reasoning_quality')
    op.drop_column('debates', 'audit_thoroughness')
    op.drop_column('debates', 'audit_fairness')
    op.drop_column('debates', 'audit_accuracy')
    op.drop_column('debates', 'con_engagement')
    op.drop_column('debates', 'con_persuasiveness')
    op.drop_column('debates', 'con_evidence')
    op.drop_column('debates', 'con_logical_consistency')
    op.drop_column('debates', 'pro_engagement')
    op.drop_column('debates', 'pro_persuasiveness')
    op.drop_column('debates', 'pro_evidence')
    op.drop_column('debates', 'pro_logical_consistency')
    # ### end Alembic commands ###
