"""add content filter excuses table

Revision ID: 2ea1c5d2fbf8
Revises: dc6525a659f3
Create Date: 2025-11-29 12:41:04.525593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea1c5d2fbf8'
down_revision: Union[str, None] = 'dc6525a659f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing debatephase enum - use PostgreSQL ENUM directly to avoid SQLAlchemy trying to create it
    from sqlalchemy.dialects.postgresql import ENUM
    debatephase_enum = ENUM('opening', 'rebuttal', 'cross_examination', 'closing', 'judgment', 'audit', name='debatephase', create_type=False)

    op.create_table('content_filter_excuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debate_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('replacement_model_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phase', debatephase_enum, nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['replacement_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_filter_excuses_debate_id'), 'content_filter_excuses', ['debate_id'], unique=False)
    op.create_index(op.f('ix_content_filter_excuses_model_id'), 'content_filter_excuses', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_filter_excuses_model_id'), table_name='content_filter_excuses')
    op.drop_index(op.f('ix_content_filter_excuses_debate_id'), table_name='content_filter_excuses')
    op.drop_table('content_filter_excuses')
    # ### end Alembic commands ###
