"""add_elo_tracking_to_debates

Revision ID: 98c35fbf9f7d
Revises: 001
Create Date: 2025-11-28 17:56:51.492962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c35fbf9f7d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('pro_elo_before', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('pro_elo_after', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_elo_before', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('con_elo_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'con_elo_after')
    op.drop_column('debates', 'con_elo_before')
    op.drop_column('debates', 'pro_elo_after')
    op.drop_column('debates', 'pro_elo_before')
    # ### end Alembic commands ###
