"""Add JSONB analysis_metadata columns for future analysis

Revision ID: dc6525a659f3
Revises: 08253d9fce42
Create Date: 2025-11-28 22:15:28.567455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc6525a659f3'
down_revision: Union[str, None] = '08253d9fce42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('analysis_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('transcript_entries', sa.Column('analysis_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_entries', 'analysis_metadata')
    op.drop_column('debates', 'analysis_metadata')
    # ### end Alembic commands ###
